name: Build and deploy an app to AKS

on:
  push:
  workflow_dispatch:

jobs:  
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
         
      - name: sonar
        run: docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest 

#      - name: sonarqube connexion
#        run: kubectl port-forward svc/sonarqube-sonarqube -n sonarqube --address 0.0.0.0 9000 &
         
      - name: sonarqube token
        run: |
          curl -u admin:admin -X POST "http://127.0.0.1:9000/api/user_tokens/generate" -d "name=mon_token"

      - name: lance sonarqube
        run: |
          sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.projectKey=sonarqube -Dsonar.sources=. -Dsonar.host.url=${{ secrets.SONAR_IP }} -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.password=${{ secrets.SONAR_PASSWORD }} -X

#      - name: Official SonarQube Scan test
#        uses: SonarSource/sonarcloud-github-action@master 
#        env:
#          SONAR_TOKEN: ${{ secrets.T }}
#          sonar.projectKey: MelkiBenjamin_deploiement-apli-kubernetes-argocd
#          sonar.organization: melkibenjamin

  